Modal pop-up
tufoinnkuo10/Personal-Portfolio pull request #15
Opened 2021-09-01 14:22 UTC by tufoinnkuo10

In this project 
- A mobile pop up template was created
- Buttons were linked to it
- all cards can be called from script
- a close button added to it

2021-09-01 15:11 UTC, hemant-soni-vst-au4 requested changes
Hi Team, 

Good job so far! 👍 
There are some issues that you still need to work on to go to the next project but you are almost there! 

![Alt Text](https://media.giphy.com/media/q6U4fbreC4Neo/giphy.gif)
## Required Changes ♻️
_Check the comments under the review._

Cheers and happy coding 😃

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. You can mention me (@hemant-soni-vst-au4) so I can see your comments and respond.


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-01 15:11 UTC, hemant-soni-vst-au4 commented on script.js
> +
- [ ] The modal pop up should be in the center for both mobile view and desktop view as per Figma design. Your modal is aligned to left in desktop view and is taking the whole width in mobile view. Kindly try to implement the modal as per Figma's design.

- [ ] The background colour of buttons is white. Kindly try to change the colour technology button's colour from grey to white.

- [ ]  On desktop view there is less margin between the projected image and description. Kindly check the below comparison and fix it.

- [ ] The icon on the source button should be aligned properly to the text. Kindly check the below design and fix it.

Your modal on Desktop view
![image](https://user-images.githubusercontent.com/53019916/131695441-a202589a-6cef-4919-9eed-1872d5e9e9cd.png)

Figma design for desktop view
![image](https://user-images.githubusercontent.com/53019916/131695575-bb59282c-7d30-41c6-bb99-9fa69695023d.png)

Your modal pop up on mobile view
![image](https://user-images.githubusercontent.com/53019916/131695796-7606ada6-249f-41f3-9165-833fbda10498.png)

Figma design for mobile view
![image](https://user-images.githubusercontent.com/53019916/131695912-4ed6088f-f042-43ac-b532-33387af2589d.png)

2021-09-02 08:06 UTC, DanteAlonsoHT requested changes
<h1>Status: Changes Required 🚫 ♻️  </h1>

Hi @tufoinnkuo10, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2021-09-02 08:06 UTC, DanteAlonsoHT commented on index.html
> +        <button class="liston-button bb1 cproject">See Project</button>
- [ ] Add more padding for your `li` elements in your popup.
- [ ] Align the bottom from the main image with the "see live" and the "see source" buttons.
- [ ] Add the right font-family for all your popup.
- [ ] Add the right "X" close icon according to the Figma design you selected.
- [ ] Add blur background when you are in your popup.

Figma design | Your design

![image](https://user-images.githubusercontent.com/60164239/131805631-c82c833a-7425-4bca-b878-5f2757e6b76a.png)

2021-09-02 08:06 UTC, DanteAlonsoHT commented on index.html
> +        <button class="liston-button bb1 cproject">See Project</button>
- [ ] Add responsive design for your popup, as you can see in the image below, when you are in the mobile version the popup can look better to show the information properly.

![image](https://user-images.githubusercontent.com/60164239/131806290-afc3fe21-b8b7-4f46-b863-cb8b28b787d0.png)

2021-09-02 16:28 UTC, Davidosky007 requested changes
## Hi @tufoinnkuo10 @MrBrN197 👋, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️
* The mobile view popup modal still needs some adjustment kindly make the necessary adjustment so that yours look as close as possible to the original design 🙏 
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2021-09-02 16:28 UTC, Davidosky007 commented on script.js
> +    const popupImage = popup.querySelector('.pop-img');
* Hi, i can see the popup modal for mobile devices isn't still looking like the original design like the previous code reviewer pointed out kindly adjust the modal on mobile view to look as close as possible as the original design 
* [ORIGINAL]
![image](https://user-images.githubusercontent.com/52497246/131881176-ba010f93-3b26-4fad-b401-8080269d71b6.png)
* [YOURS]
![image](https://user-images.githubusercontent.com/52497246/131881238-c84ddf08-e125-40b7-91d9-81c293c8cd29.png)

2021-09-03 06:31 UTC, merged